version: '3'  # Docker Composeのバージョンを指定

services:  # サービスの定義を開始
  web:  # 'web'という名前のサービスを定義
    build:
      context: .  # Dockerfileがあるディレクトリを指定
      dockerfile: Dockerfile  # 使用するDockerfileを指定
    command: npm run dev  # コンテナ内で実行するコマンド（開発用サーバーを起動）
    volumes:  # ボリュームのマウントを定義
      - .:/usr/src/app  # DockerfileのWORKDIRと一致させる
      - /usr/src/app/node_modules  # node_modulesはコンテナ内に保持（ホストと共有しない）
    ports:  # ポートのマッピングを定義
      - "3000:3000"

